-- userId is nullable: NULL means a default (system) subcategory shared by all users.
CREATE TABLE SubCategories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT REFERENCES Users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    name TEXT NOT NULL,
    icon TEXT,
    categoryId BIGINT NOT NULL REFERENCES Categories (id) ON UPDATE CASCADE ON DELETE CASCADE,
    createdAt TIMESTAMPTZ NOT NULL,
    updatedAt TIMESTAMPTZ NOT NULL
);
