-- userId is nullable: NULL means a default (system) tag shared by all users.
CREATE TABLE ItemTags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT REFERENCES Users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    name TEXT NOT NULL,
    colour TEXT,
    createdAt TIMESTAMPTZ NOT NULL,
    updatedAt TIMESTAMPTZ NOT NULL
);
